# GitFlic CI/CD Configuration for NFS Mamont Rust Project

image: registry.gitflic.ru/project/yadro/nfs-mamont/rust:1.88.0-slim-bullseye

stages:
  - fmt
  - clippy
  - build
  - test

fmt:
  stage: fmt
  script:
    - rustup component add rustfmt
    - cargo fmt --check

clippy:
  stage: clippy
  script:
    - rustup component add clippy
    - cargo clippy -- -Dwarnings
  needs:
    - fmt

build:
  stage: build
  script:
    - cargo build --release
  needs:
    - clippy

test:
  stage: test
  script:
    - cargo test
  needs:
    - build
