# GitFlic CI/CD Configuration for NFS Mamont Rust Project

variables:
  # Rust environment variables
  CARGO_HOME: "${CI_PROJECT_DIR}/.cargo"
  RUSTUP_HOME: "${CI_PROJECT_DIR}/.rustup"
  RUST_BACKTRACE: "1"
  CARGO_TERM_COLOR: "always"
  CARGO_INCREMENTAL: "0"
  RUSTFLAGS: "-Dwarnings"
  
  # Cache settings
  CARGO_CACHE_KEY: "cargo-${CI_JOB_NAME}-${CI_COMMIT_REF_SLUG}"
  
  # Pipeline settings
  PIPELINE_TIMEOUT: "3600"  # 1 hour timeout
  JOB_RESTART_TIMEOUT: "300"  # 5 minutes restart timeout

# Pipeline lifetime settings (30 days)
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

# Pipeline stages
stages:
  - setup
  - quality
  - build
  - test
  - security
  - documentation
  - docker
  - deploy

# Caching to speed up builds
.cache_template: &cache_template
  cache:
    key: "${CARGO_CACHE_KEY}"
    paths:
      - .cargo/
      - .rustup/
      - target/
    policy: pull-push

# Base template for Rust jobs
.rust_base:
  image: rust:1.83
  before_script:
    - export PATH="$CARGO_HOME/bin:$PATH"
    - |
      if [ ! -f "$CARGO_HOME/bin/cargo" ]; then
        echo "Installing Rust toolchain..."
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
        source $CARGO_HOME/env
        rustup toolchain install stable --profile minimal
        rustup default stable
        rustup component add clippy rustfmt
      fi
    - source $CARGO_HOME/env || true
    - rustc --version
    - cargo --version
  <<: *cache_template

# Environment setup
setup:rust:
  extends: .rust_base
  stage: setup
  script:
    - echo "Rust environment setup completed"
    - cargo fetch --locked
  artifacts:
    expire_in: 1 hour
    paths:
      - .cargo/
      - .rustup/

# Code formatting check
format:check:
  extends: .rust_base
  stage: quality
  needs: ["setup:rust"]
  script:
    - echo "Checking code formatting..."
    - cargo fmt --all -- --check
  allow_failure: false

# Clippy analysis
clippy:analysis:
  extends: .rust_base
  stage: quality
  needs: ["setup:rust"]
  script:
    - echo "Running clippy analysis..."
    - cargo clippy --workspace --all-targets --all-features -- -D warnings -D clippy::all
  artifacts:
    expire_in: 1 week
    reports:
      junit: target/clippy-report.xml
    when: always

# Cargo check
cargo:check:
  extends: .rust_base
  stage: quality
  needs: ["setup:rust"]
  script:
    - echo "Running cargo check..."
    - cargo check --workspace --all-targets --all-features

# Debug build
build:debug:
  extends: .rust_base
  stage: build
  needs: ["format:check", "clippy:analysis", "cargo:check"]
  script:
    - echo "Building debug version..."
    - cargo build --workspace --all-targets --all-features
  artifacts:
    expire_in: 1 day
    paths:
      - target/debug/

# Release build
build:release:
  extends: .rust_base
  stage: build
  needs: ["format:check", "clippy:analysis", "cargo:check"]
  script:
    - echo "Building release version..."
    - cargo build --release --workspace --all-targets --all-features
  artifacts:
    expire_in: 1 week
    paths:
      - target/release/
  only:
    - main
    - merge_requests

# Build examples
build:examples:
  extends: .rust_base
  stage: build
  needs: ["build:debug"]
  script:
    - echo "Building examples..."
    - cargo build --examples --all-features
    - cargo build --example mirrorfs --all-features
    - cargo build --example demofs --all-features
  artifacts:
    expire_in: 1 day
    paths:
      - target/debug/examples/
  only:
    - main
    - merge_requests

# Unit tests
test:unit:
  extends: .rust_base
  stage: test
  needs: ["build:debug"]
  script:
    - echo "Running unit tests..."
    - cargo test --workspace --lib --all-features -- --nocapture
  artifacts:
    expire_in: 1 week
    reports:
      junit: target/unit-test-results.xml
    when: always

# Integration tests
test:integration:
  extends: .rust_base
  stage: test
  needs: ["build:debug"]
  script:
    - echo "Running integration tests..."
    - cargo test --workspace --test "*" --all-features -- --nocapture
  artifacts:
    expire_in: 1 week
    reports:
      junit: target/integration-test-results.xml
    when: always

# Documentation tests
test:doc:
  extends: .rust_base
  stage: test
  needs: ["build:debug"]
  script:
    - echo "Running documentation tests..."
    - cargo test --workspace --doc --all-features

# Security audit
security:audit:
  extends: .rust_base
  stage: security
  needs: ["setup:rust"]
  before_script:
    - export PATH="$CARGO_HOME/bin:$PATH"
    - |
      if [ ! -f "$CARGO_HOME/bin/cargo" ]; then
        echo "Installing Rust toolchain..."
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
        source $CARGO_HOME/env
        rustup toolchain install stable --profile minimal
        rustup default stable
        rustup component add clippy rustfmt
      fi
    - source $CARGO_HOME/env || true
    - rustc --version
    - cargo --version
    - cargo install cargo-audit --locked || true
  script:
    - echo "Running security audit..."
    - cargo audit --json > target/audit-report.json || true
    - cargo audit
  artifacts:
    expire_in: 1 week
    paths:
      - target/audit-report.json
    when: always
  allow_failure: true

# Check for outdated dependencies
security:outdated:
  extends: .rust_base
  stage: security
  needs: ["setup:rust"]
  before_script:
    - export PATH="$CARGO_HOME/bin:$PATH"
    - |
      if [ ! -f "$CARGO_HOME/bin/cargo" ]; then
        echo "Installing Rust toolchain..."
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
        source $CARGO_HOME/env
        rustup toolchain install stable --profile minimal
        rustup default stable
        rustup component add clippy rustfmt
      fi
    - source $CARGO_HOME/env || true
    - rustc --version
    - cargo --version
    - cargo install cargo-outdated --locked || true
  script:
    - echo "Checking for outdated dependencies..."
    - cargo outdated --root-deps-only > target/outdated-report.txt || true
  artifacts:
    expire_in: 1 week
    paths:
      - target/outdated-report.txt
    when: always
  allow_failure: true

# Generate documentation
docs:generate:
  extends: .rust_base
  stage: documentation
  needs: ["build:release"]
  script:
    - echo "Generating documentation..."
    - cargo doc --workspace --all-features --no-deps --document-private-items
  artifacts:
    expire_in: 1 month
    paths:
      - target/doc/
  only:
    - main

# Code coverage analysis
coverage:analysis:
  extends: .rust_base
  stage: documentation
  needs: ["test:unit", "test:integration"]
  before_script:
    - export PATH="$CARGO_HOME/bin:$PATH"
    - |
      if [ ! -f "$CARGO_HOME/bin/cargo" ]; then
        echo "Installing Rust toolchain..."
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
        source $CARGO_HOME/env
        rustup toolchain install stable --profile minimal
        rustup default stable
        rustup component add clippy rustfmt
      fi
    - source $CARGO_HOME/env || true
    - rustc --version
    - cargo --version
    - cargo install cargo-tarpaulin --locked || true
  script:
    - echo "Generating coverage report..."
    - mkdir -p target/coverage
    - cargo tarpaulin --workspace --all-features --out xml --out html --output-dir target/coverage --timeout 300
  artifacts:
    expire_in: 1 month
    paths:
      - target/coverage/
    reports:
      coverage_report:
        coverage_format: cobertura
        path: target/coverage/cobertura.xml
  coverage: '/(\d+\.\d+)% coverage/'
  only:
    - main

# Performance benchmarks
benchmarks:performance:
  extends: .rust_base
  stage: documentation
  needs: ["build:release"]
  script:
    - echo "Running performance benchmarks..."
    - |
      if [ -d "benches" ] || grep -q "\\[\\[bench\\]\\]" Cargo.toml; then
        echo "Running benchmarks..."
        cargo bench --workspace --all-features -- --output-format json > target/benchmark-results.json || true
      else
        echo "No benchmarks found, skipping..."
        echo "{}" > target/benchmark-results.json
      fi
  artifacts:
    expire_in: 1 month
    paths:
      - target/benchmark-results.json
  only:
    - main
  allow_failure: true

# Deploy artifacts (main branches only)
deploy:artifacts:
  extends: .rust_base
  stage: deploy
  needs: 
    - "build:release"
    - "docs:generate"
    - "coverage:analysis"
  script:
    - echo "Deploying artifacts..."
    - echo "Release binaries and documentation are ready for deployment"
  artifacts:
    expire_in: 3 months
    paths:
      - target/release/
      - target/doc/
      - target/coverage/
  only:
    - main
  when: manual

# Docker build and push
.docker_base:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1
  before_script:
    - echo "Logging into GitFlic Docker registry..."
    - echo "$DOCKER_REGISTRY_PASSWORD" | docker login $DOCKER_REGISTRY -u "$DOCKER_REGISTRY_USER" --password-stdin

# Build Docker image
docker:build:
  extends: .docker_base
  stage: docker
  needs: ["build:release"]
  script:
    - echo "Building Docker image..."
    - |
      IMAGE_TAG="${DOCKER_REGISTRY}/${DOCKER_PROJECT_PATH}/${DOCKER_IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
      LATEST_TAG="${DOCKER_REGISTRY}/${DOCKER_PROJECT_PATH}/${DOCKER_IMAGE_NAME}:latest"
      
      echo "Building image: $IMAGE_TAG"
      docker build --build-arg BUILDKIT_INLINE_CACHE=1 \
        --cache-from $LATEST_TAG \
        -t $IMAGE_TAG \
        -t $LATEST_TAG \
        .
      
      echo "Built image successfully"
      docker images | grep nfs-mamont
  artifacts:
    expire_in: 1 hour
    reports:
      dotenv: docker-build.env
  only:
    - main
    - merge_requests

# Push Docker image to registry
docker:push:
  extends: .docker_base
  stage: docker
  needs: ["docker:build"]
  script:
    - echo "Pushing Docker image to registry..."
    - |
      IMAGE_TAG="${DOCKER_REGISTRY}/${DOCKER_PROJECT_PATH}/${DOCKER_IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
      LATEST_TAG="${DOCKER_REGISTRY}/${DOCKER_PROJECT_PATH}/${DOCKER_IMAGE_NAME}:latest"
      
      echo "Pushing image: $IMAGE_TAG"
      docker push $IMAGE_TAG
      
      if [ "$CI_COMMIT_BRANCH" = "main" ]; then
        echo "Pushing latest tag: $LATEST_TAG"
        docker push $LATEST_TAG
      fi
      
      echo "Image pushed successfully"
      echo "IMAGE_TAG=$IMAGE_TAG" >> docker-push.env
      echo "LATEST_TAG=$LATEST_TAG" >> docker-push.env
  artifacts:
    expire_in: 1 week
    reports:
      dotenv: docker-push.env
  only:
    - main
  when: manual

# Security scan for Docker image
docker:security:
  extends: .docker_base
  stage: docker
  needs: ["docker:build"]
  before_script:
    - echo "Installing Trivy for container security scanning..."
    - apk add --no-cache curl
    - |
      curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
  script:
    - echo "Scanning Docker image for vulnerabilities..."
    - |
      IMAGE_TAG="${DOCKER_REGISTRY}/${DOCKER_PROJECT_PATH}/${DOCKER_IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
      
      echo "Scanning image: $IMAGE_TAG"
      trivy image --format json --output trivy-report.json $IMAGE_TAG || true
      trivy image --format table $IMAGE_TAG || true
  artifacts:
    expire_in: 1 week
    paths:
      - trivy-report.json
    when: always
  allow_failure: true
  only:
    - main
    - merge_requests

# Deploy Docker container (manual)
deploy:docker:
  extends: .docker_base
  stage: deploy
  needs: 
    - "docker:push"
    - "docker:security"
  script:
    - echo "Docker deployment ready..."
    - |
      IMAGE_TAG="${DOCKER_REGISTRY}/${DOCKER_PROJECT_PATH}/${DOCKER_IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
      
      echo "Image ready for deployment: $IMAGE_TAG"
      echo "To run the container:"
      echo "docker run -d -p 2049:2049 --name nfs-mamont $IMAGE_TAG"
      echo ""
      echo "To mount NFS:"
      echo "sudo mount -t nfs -o vers=3,tcp,port=2049 <container-ip>:/ /mnt/nfs"
  artifacts:
    expire_in: 3 months
    paths:
      - docker-push.env
  only:
    - main
  when: manual

# Post-execution cleanup
cleanup:
  stage: .post
  image: alpine:latest
  script:
    - echo "Performing cleanup..."
    - find target -name "*.tmp" -delete || true
    - find target -name "*.rlib" -mtime +7 -delete || true
    - find target -name "*.rmeta" -mtime +7 -delete || true
  when: always
  allow_failure: true