# GitFlic CI/CD Configuration for NFS Mamont Rust Project

image: ubuntu:latest

before_script:
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  - . "$HOME/.cargo/env"
  - rustup default stable

stages:
  - fmt
  - clippy
  - build
  - test

fmt:
  stage: fmt
  script:
    - cargo fmt --check

clippy:
  stage: clippy
  script:
    - cargo clippy -- -Dwarnings
  needs:
    - fmt

build:
  stage: build
  script:
    - cargo build --release
  needs:
    - clippy

test:
  stage: test
  script:
    - cargo test
  needs:
    - build
